import { db, Product, Service } from 'astro:db';

// https://astro.build/db/seed



export default async function seed() {
	await db.insert(Product).values([
		{ id: '1', name: 'HYALU7 BIOSERUM', price: 100, summary: 'Serum relleno de arrugas y efecto volumen tridimensional.', description: 'Serum relleno de arrugas y efecto volumen tridimensional. Actúa en simultáneo en distintos niveles cutáneos. Logra un film protector de 24 horas en la epidermis y un efecto de relleno hídrico en dermis para minimizar las arrugas desde el interior', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'HYALU7' },
		{ id: '2', name: 'CONTROL BROSSAGE', price: 200, summary: 'Higieniza la piel eliminando los residuos grasos, sin dejar la piel tirante o reseca.', description: 'Higieniza la piel eliminando los residuos grasos, sin dejar la piel tirante o reseca. Su espuma es refrescante, suavizante y de grata acción limpiadora.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Control Brossage' },
		{ id: '3', name: 'CONTROL BIO DETOX', price: 150, summary: 'Serum equilibrante para piel grasa.', description: 'Fluido ideado para mejorar los desbalances del microbioma cutaneo, con efecto detox y regulador. Refuerza la función protectora de la piel y aporta, suavidad, frescura y luz interior. Ideal para tratar poros muy visibles.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Control Bio Detox' },
		{ id: '4', name: 'CONTROL FLUID', price: 180, summary: 'Fluido humectante para pieles grasas.', description: 'Ideal para pieles oleosas y zonas deshidratadas, ya que regula la grasitud como la tirantez de la deshidratación. Ideal para climas húmedos y cálidos, porque humecta la piel sin aportar untuosidad.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Control Fluid' },
		{ id: '5', name: 'ECLAIR LUMIBLEND', price: 220, summary: 'Serum despigmentante para tratar manchas de diferentes orígenes.', description: 'Ideal para todo tipo de pieles oscurecidas, gruesas y opacas. Disminuye la intensidad de la mancha progresivamente con una fórmula libre de riesgos de irritación. Apto para todo tipo de piel, en cualquier momento del año.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Eclair Lumiblend' },
		{ id: '6', name: 'VITA C BROSSAGE', price: 200, summary: 'Espuma limpiadora.', description: 'Higieniza la piel eliminando residuos grasos, sin dejar la piel reseca. Su espuma es refrescante y de grata acción limpiadora.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Vita C Brossage' },
		{ id: '7', name: 'VITA C FLUID', price: 210, summary: 'Emulsión antioxidante con micronutrientes.', description: 'Emulsión antioxidante con micronutrientes que revitaliza y humecta las pieles más apagadas devolviendo la luminocidad.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Vita C Fluid' },
		{ id: '8', name: 'HYALU CREAM', price: 170, summary: 'Emulsión humectante que aporta y retiene la humedad.', description: 'Ideal para todo tipo de pieles y edades. Posee una textura elástica y adaptable. Mejora suavidad de la piel y atenúa arrugas. Ideal para el uso diario.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Hyalu Cream' },
		{ id: '9', name: 'VITA A MULTISERUM', price: 230, summary: 'Serum multivitaminas que repara y reequilibra.', description: 'Representa un verdadero soporte antiedad integral con 5 vitaminas antioxidantes. El resultado es una piel más nutrida, húmeda, menos arrugas profundas, mejor renovación celular y mejor función de barrera.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Vita A Multiserum' },
		{ id: '10', name: 'URBAN LAIT', price: 190, summary: 'Fotoprotector +35, incoloro y no graso.', description: 'Textura fluída, fresca y con alta protección con un acabado no graso. Especialmente diseñado para pieles grasas y en climas cálidos y húmedos.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Urban Lait' },
		{ id: '11', name: 'PURE MEGA TONIC', price: 160, summary: 'Loción renovadora.', description: 'Loción renovadora que ablanda y afina la piel mejorando sus condiciones para la higiente profunda. Ayuda a emparejar el tono y suavidad al tacto.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Pure Mega Tonic' },
		{ id: '12', name: 'FRESH CLEAN', price: 120, summary: 'Gel limpiador de 150ml para pieles sensibles.', description: 'Con textura fresca y una eficaz acción limpiadora. Formulado para desmaquillar e higienizar el rostro sin irritaciones.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Fresh Clean' }
	]);


	await db.insert(Service).values([
		{ id: '100', name: 'Limpieza facial prunda', price: 90, summary: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!', description: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!. En 10 pasos mejoro la salud y la apariencia de tu piel, eliminando impurezas y revitalizándola. Limpio en profundidad, elimino las células muertas, realizo extracciones de puntos negros, quistes de millium y pústulas, coloco sueros para tratar cada problemática e hidrato en todos los niveles dejando tu piel impecable. 💧🌟', recomendation: '', image: '/img/higieneFacial.jpeg', alt: 'Limpieza facial' },
		{ id: '101', name: 'Limpieza facial + Dermaplaning', price: 100, summary: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? 😍', description: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? 😍. Si tu piel es apta, el dermaplaning es el tratamiento perfecto. Utiliza un bisturí descartable para eliminar células muertas y vello facial, mejorando la textura, reduciendo arrugas finas y cicatrices por acné. Además, proporciona una exfoliación profunda que estimula la renovación celular. El resultado es una piel más uniforme y luminosa, ideal para mantener durante todo el año. ✨', recomendation: '', image: '/img/limpiezaFacial+dermapiling.jpeg', alt: 'limpieza facial y dermapiling' },
		{ id: '102', name: 'Limpieza facial + Dermapen', price: 120, summary: '¿Rejuvenecer la piel sin cirugía ni tiempos de recuperación prolongados? 😍', description: '¿Rejuvenecer la piel sin cirugía ni tiempos de recuperación prolongados? 😍. El dermapen utiliza microagujas para estimular la regeneración de la piel, logrando la reducción de arrugas, líneas finas y cicatrices. Además, al añadir una ampolla específica durante el tto, potenciamos los resultados y maximizamos los beneficios de cada sustancia aplicada. ✨. Incluye masajes con Cryo Sticks, esferas de metal que proporcionan una sensación refrescante y relajante con frío localizado, ayudando a reducir la inflamación post-tratamiento. Además, un masaje relajante en hombros, cervicales y cabeza para un toque de bienestar adicional. 💆‍♀️', recomendation: '⚠️ Este tto no es apto para embarazadas, anticoagulados, diabéticos, ni personas que cursen un proceso inflamatorio de la piel.', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen' },
		{ id: '103', name: 'Limpieza facial prunda', price: 90, summary: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!', description: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!. En 10 pasos mejoro la salud y la apariencia de tu piel, eliminando impurezas y revitalizándola. Limpio en profundidad, elimino las células muertas, realizo extracciones de puntos negros, quistes de millium y pústulas, coloco sueros para tratar cada problemática e hidrato en todos los niveles dejando tu piel impecable. 💧🌟', recomendation: '', image: '/img/higieneFacial.jpeg', alt: 'Limpieza facial' },
		{ id: '104', name: 'Limpieza facial + Dermaplaning', price: 100, summary: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? 😍', description: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? 😍. Si tu piel es apta, el dermaplaning es el tratamiento perfecto. Utiliza un bisturí descartable para eliminar células muertas y vello facial, mejorando la textura, reduciendo arrugas finas y cicatrices por acné. Además, proporciona una exfoliación profunda que estimula la renovación celular. El resultado es una piel más uniforme y luminosa, ideal para mantener durante todo el año. ✨', recomendation: '', image: '/img/limpiezaFacial+dermapiling.jpeg', alt: 'limpieza facial y dermapiling' },
		{ id: '105', name: 'Limpieza facial + Dermapen', price: 120, summary: '¿Rejuvenecer la piel sin cirugía ni tiempos de recuperación prolongados? 😍', description: '¿Rejuvenecer la piel sin cirugía ni tiempos de recuperación prolongados? 😍. El dermapen utiliza microagujas para estimular la regeneración de la piel, logrando la reducción de arrugas, líneas finas y cicatrices. Además, al añadir una ampolla específica durante el tto, potenciamos los resultados y maximizamos los beneficios de cada sustancia aplicada. ✨. Incluye masajes con Cryo Sticks, esferas de metal que proporcionan una sensación refrescante y relajante con frío localizado, ayudando a reducir la inflamación post-tratamiento. Además, un masaje relajante en hombros, cervicales y cabeza para un toque de bienestar adicional. 💆‍♀️', recomendation: '⚠️ Este tto no es apto para embarazadas, anticoagulados, diabéticos, ni personas que cursen un proceso inflamatorio de la piel.', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen' },
	]);
}
