import { db, Product, Service } from 'astro:db';

// https://astro.build/db/seed



export default async function seed() {
	await db.insert(Product).values([
		{ id: '1', name: 'HYALU7 BIOSERUM', price: 100, summary: 'Serum relleno de arrugas y efecto volumen tridimensional.', description: 'Serum relleno de arrugas y efecto volumen tridimensional. Actúa en simultáneo en distintos niveles cutáneos. Logra un film protector de 24 horas en la epidermis y un efecto de relleno hídrico en dermis para minimizar las arrugas desde el interior', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'HYALU7', category: 'Serum' },
		{ id: '2', name: 'CONTROL BROSSAGE', price: 200, summary: 'Higieniza la piel eliminando los residuos grasos, sin dejar la piel tirante o reseca.', description: 'Higieniza la piel eliminando los residuos grasos, sin dejar la piel tirante o reseca. Su espuma es refrescante, suavizante y de grata acción limpiadora.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Control Brossage', category: 'Serum' },
		{ id: '3', name: 'CONTROL BIO DETOX', price: 150, summary: 'Serum equilibrante para piel grasa.', description: 'Fluido ideado para mejorar los desbalances del microbioma cutaneo, con efecto detox y regulador. Refuerza la función protectora de la piel y aporta, suavidad, frescura y luz interior. Ideal para tratar poros muy visibles.', recomendation: '', image: '/img/ControlBioDetox.jpeg', alt: 'Control Bio Detox', category: 'Serum' },
		{ id: '4', name: 'CONTROL FLUID', price: 180, summary: 'Fluido humectante para pieles grasas.', description: 'Ideal para pieles oleosas y zonas deshidratadas, ya que regula la grasitud como la tirantez de la deshidratación. Ideal para climas húmedos y cálidos, porque humecta la piel sin aportar untuosidad.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Control Fluid', category: 'Limpiadores' },
		{ id: '5', name: 'ECLAIR LUMIBLEND', price: 220, summary: 'Serum despigmentante para tratar manchas de diferentes orígenes.', description: 'Ideal para todo tipo de pieles oscurecidas, gruesas y opacas. Disminuye la intensidad de la mancha progresivamente con una fórmula libre de riesgos de irritación. Apto para todo tipo de piel, en cualquier momento del año.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Eclair Lumiblend', category: 'Limpiadores' },
		{ id: '6', name: 'VITA C BROSSAGE', price: 200, summary: 'Espuma limpiadora.', description: 'Higieniza la piel eliminando residuos grasos, sin dejar la piel reseca. Su espuma es refrescante y de grata acción limpiadora.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Vita C Brossage', category: 'Limpiadores' },
		{ id: '7', name: 'VITA C FLUID', price: 210, summary: 'Emulsión antioxidante con micronutrientes.', description: 'Emulsión antioxidante con micronutrientes que revitaliza y humecta las pieles más apagadas devolviendo la luminocidad.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Vita C Fluid', category: 'Hidrantes' },
		{ id: '8', name: 'HYALU CREAM', price: 170, summary: 'Emulsión humectante que aporta y retiene la humedad.', description: 'Ideal para todo tipo de pieles y edades. Posee una textura elástica y adaptable. Mejora suavidad de la piel y atenúa arrugas. Ideal para el uso diario.', recomendation: '', image: '/img/HyaluCream.jpeg', alt: 'Hyalu Cream', category: 'Hidrantes' },
		{ id: '9', name: 'VITA A MULTISERUM', price: 230, summary: 'Serum multivitaminas que repara y reequilibra.', description: 'Representa un verdadero soporte antiedad integral con 5 vitaminas antioxidantes. El resultado es una piel más nutrida, húmeda, menos arrugas profundas, mejor renovación celular y mejor función de barrera.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Vita A Multiserum', category: 'FPS' },
		{ id: '10', name: 'URBAN LAIT', price: 190, summary: 'Fotoprotector +35, incoloro y no graso.', description: 'Textura fluída, fresca y con alta protección con un acabado no graso. Especialmente diseñado para pieles grasas y en climas cálidos y húmedos.', recomendation: '', image: '/img/UrbanLait.jpeg', alt: 'Urban Lait', category: 'FPS' },
		{ id: '11', name: 'PURE MEGA TONIC', price: 160, summary: 'Loción renovadora.', description: 'Loción renovadora que ablanda y afina la piel mejorando sus condiciones para la higiente profunda. Ayuda a emparejar el tono y suavidad al tacto.', recomendation: '', image: '/img/Hyalu7.jpeg', alt: 'Pure Mega Tonic', category: 'FPS' },
		{ id: '12', name: 'FRESH CLEAN', price: 120, summary: 'Gel limpiador de 150ml para pieles sensibles.', description: 'Con textura fresca y una eficaz acción limpiadora. Formulado para desmaquillar e higienizar el rostro sin irritaciones.', recomendation: '', image: '/img/ControlBrossage.jpeg', alt: 'Fresh Clean', category: 'FPS' },
	]);


	await db.insert(Service).values([
		{ id: '100', name: 'Limpieza Facial Profunda', price: 90, summary: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!', description: 'chau celulas muertas acumuladas, puntos negros,quistes de milium y postulas!. En 10 pasos mejoro la salud y la apariencia de tu piel, eliminando impurezas y revitalizándola. Limpio en profundidad, elimino las células muertas, realizo extracciones de puntos negros, quistes de millium y pústulas, coloco sueros para tratar cada problemática e hidrato en todos los niveles dejando tu piel impecable.', recomendation: '', image: '/img/higieneFacial.jpeg', alt: 'Limpieza facial', benefits: '', care: '' },
		{ id: '101', name: 'Limpieza Facial + Dermaplaning', price: 110, summary: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? ', description: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? . Si tu piel es apta, el dermaplaning es el tratamiento perfecto. Utiliza un bisturí descartable para eliminar células muertas y vello facial, mejorando la textura, reduciendo arrugas finas y cicatrices por acné. Además, proporciona una exfoliación profunda que estimula la renovación celular. El resultado es una piel más uniforme y luminosa, ideal para mantener durante todo el año. ', recomendation: '', image: '/img/limpiezaFacial+dermapiling.jpeg', alt: 'limpieza facial y dermapiling', benefits: '', care: '' },
		{ id: '102', name: 'Limpieza Facial + Terapia Led', price: 100, summary: 'Disfruta de una piel fresca y renovada con nuestro tratamiento de Limpieza Facial + Terapia LED.', description: 'Disfruta de una piel fresca y renovada con nuestro tratamiento de Limpieza Facial + Terapia LED. Comenzamos con una limpieza profunda que elimina impurezas y prepara tu piel para los beneficios de la terapia LED, que estimula la producción de colágeno, reduce la inflamación y mejora la textura de la piel. Ideal para todo tipo de piel, este tratamiento purifica, rejuvenece y deja tu rostro radiante, con resultados visibles y duraderos. ¡Perfecto para lucir una piel saludable y revitalizada!', recomendation: '', image: '/img/limpiezaFacial+tratamientoLed.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{ id: '103', name: 'Microneedling facial', price: 135, summary: 'El Microneedling Facial es un tratamiento innovador que utiliza microagujas para estimular la regeneración celular y mejorar la textura de la piel.', description: 'El Microneedling Facial es un tratamiento innovador que utiliza microagujas para estimular la regeneración celular y mejorar la textura de la piel. A través de pequeñas punciones, se activan los procesos naturales de reparación de la piel, promoviendo la producción de colágeno y elastina. Este tratamiento ayuda a reducir cicatrices, líneas finas, poros dilatados y manchas, dejando la piel más firme, suave y luminosa. Es ideal para quienes buscan una solución efectiva y mínimamente invasiva para mejorar la apariencia general del rostro, logrando resultados visibles con poco tiempo de recuperación.', recomendation: '', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{ id: '104', name: 'Tratamiento para Manchas', price: 95, summary: 'Nuestro Tratamiento para Manchas está diseñado para aclarar y unificar el tono de la piel, eliminando manchas causadas por el sol, el envejecimiento o el acné.', description: 'Nuestro Tratamiento para Manchas está diseñado para aclarar y unificar el tono de la piel, eliminando manchas causadas por el sol, el envejecimiento o el acné. Utilizamos técnicas avanzadas y productos específicos que ayudan a reducir la pigmentación y promover una piel más luminosa y uniforme. Resultados visibles en pocas sesiones, para que luzcas una piel radiante y sin imperfecciones. Ideal para todo tipo de piel.', recomendation: '', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{ id: '105', name: 'Facial para Piel Sensible y Rosácea', price: 110, summary: 'Nuestro Facial para Piel Sensible y Rosácea está especialmente formulado para calmar, hidratar y fortalecer las pieles delicadas o con rosácea. ', description: 'Nuestro Facial para Piel Sensible y Rosácea está especialmente formulado para calmar, hidratar y fortalecer las pieles delicadas o con rosácea. Utilizamos ingredientes suaves y de acción antiinflamatoria que ayudan a reducir el enrojecimiento, la irritación y la incomodidad, restaurando el equilibrio de la piel. Ideal para quienes buscan un tratamiento gentil pero efectivo para su piel sensible.', recomendation: '', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{ id: '106', name: 'Tratamiento de Acné + Alta Frecuencia', price: 150, summary: 'Nuestro Tratamiento para Acné + Alta Frecuencia está diseñado para combatir el acné de manera efectiva y duradera.', description: 'Nuestro Tratamiento para Acné + Alta Frecuencia está diseñado para combatir el acné de manera efectiva y duradera. Combinamos una limpieza profunda con la tecnología de alta frecuencia, que ayuda a eliminar bacterias, reducir la inflamación y acelerar la cicatrización de las lesiones. La alta frecuencia también favorece la regeneración celular, mejorando la textura de la piel y minimizando marcas de acné. Ideal para pieles con brotes activos o propensas al acné, este tratamiento te ayudará a lograr una piel más limpia, equilibrada y libre de imperfecciones.', recomendation: '', image: '/img/limpiezaFacial+dermapen.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{
			id: '107', name: 'Biorepeel CL3', price: 200, summary: 'Un tratamiento facial innovador y altamente efectivo. El Biorepeel utiliza una combinación de ácidos como el ácido salicílico, el ácido láctico y el ácido tricloroacético (TCA) para proporcionar una exfoliación controlada y renovar la piel.', description: 'Un tratamiento facial innovador y altamente efectivo. El Biorepeel utiliza una combinación de ácidos como el ácido salicílico, el ácido láctico y el ácido tricloroacético (TCA) para proporcionar una exfoliación controlada y renovar la piel. Entre sus múltiples beneficios para la piel, ayuda a mejorar la textura y la luminosidad de la piel, reduciendo la apariencia de arrugas, manchas y cicatrices. También promueve la formación de colágeno, mejorando la elasticidad y la firmeza de la piel. Este tratamiento es adecuado para diferentes tipos de piel y se puede personalizar según las necesidades individuales. En verbena evaluarán tu piel y ajustarán la formulación del Biorepeel para ofrecerte los mejores resultados.', recomendation: '', image: '/img/higieneFacial.jpeg', alt: 'Limpieza facial', benefits: [
				'Sin inyecciones',
				'No requiere anestesia',
				'Rápido',
				'Resultado instantáneo',
				'Multifuncional',
				'Libre de amoniaco',
				'Aplicable para todas las edades',
				'Apto para todo el cuerpo',
				'Puede usarse todo el año',
				'No aumenta la fotosensibilidad'
			]
			, care: ''
		},
		{ id: '108', name: 'Limpieza Facial Profunda de Espalda', price: 130, summary: 'El tratamiento de Limpieza Facial Profunda de Espalda elimina impurezas, exceso de grasa y células muertas, dejando la piel limpia y libre de imperfecciones.', description: 'El tratamiento de Limpieza Facial Profunda de Espalda elimina impurezas, exceso de grasa y células muertas, dejando la piel limpia y libre de imperfecciones. Ideal para combatir el acné y mejorar la textura de la piel en esta zona. Luciendo una espalda suave, equilibrada y radiante.', recomendation: '', image: '/img/higieneFacial.jpeg', alt: 'Limpieza facial', benefits: '', care: '' },
		{ id: '109', name: 'Lifting de Pestañas', price: 100, summary: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? ', description: '¿Te copa la idea de hacerte un peeling apto para todo el año o eliminar esos vellitos que opacan y le otorgan textura a tu rostro? . Si tu piel es apta, el dermaplaning es el tratamiento perfecto. Utiliza un bisturí descartable para eliminar células muertas y vello facial, mejorando la textura, reduciendo arrugas finas y cicatrices por acné. Además, proporciona una exfoliación profunda que estimula la renovación celular. El resultado es una piel más uniforme y luminosa, ideal para mantener durante todo el año. ', recomendation: '', image: '/img/liftingPestanas2.jpeg', alt: 'limpieza facial y dermapiling', benefits: '', care: '' },
		{ id: '110', name: 'Laminado de Cejas', price: 120, summary: 'Transforma tu mirada con nuestro servicio de Laminado de Cejas. Diseño personalizado, resultados naturales y duraderos que realzan tu expresión sin esfuerzo.  Lucí unas cejas perfectas y definidas todo el día.', description: 'Transforma tu mirada con nuestro servicio de Laminado de Cejas. Diseño personalizado, resultados naturales y duraderos que realzan tu expresión sin esfuerzo.  Lucí unas cejas perfectas y definidas todo el día.', recomendation: '', image: '/img/laminadoCejas.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: '' },
		{
			id: '111', name: 'Lifting de Pestañas + Tinte + Botox', price: 120, summary: 'Resalta tu mirada con nuestro Lifting de Pestañas + Tinte + Botox. El lifting riza tus pestañas, el tinte las oscurece y el Botox las fortalece, dejándolas más voluminosas y saludables.', description: 'Resalta tu mirada con nuestro Lifting de Pestañas + Tinte + Botox. El lifting riza tus pestañas, el tinte las oscurece y el Botox las fortalece, dejándolas más voluminosas y saludables. ¡Olvídate del rímel y disfruta de unas pestañas naturales y definidas!', recomendation: '', image: '/img/laminadoCejas.jpeg', alt: 'Limpieza facial con dermapen', benefits: '', care: [
				'Evite los productos grasos: Antes del tratamiento, evite usar productos aceitosos alrededor de los ojos, ya que pueden interferir con la efectividad del levantamiento.',
				'No use rizadores de pestañas: No use un rizador de pestañas durante al menos 24 horas antes del procedimiento para evitar dañar o debilitar sus pestañas naturales.',
				'Quitar el maquillaje: Asegúrese de que sus pestañas estén completamente limpias y libres de residuos de maquillaje.'
			]
		},
	]);
}
